name: build-and-test-cardiac-api

on:
  push:
    branches: [ "**" ]
    paths:
      - "w9/d3/cardiac/**"
      - ".github/workflows/cardiac-build-test.yml"
  pull_request:
    branches: [ "**" ]
    paths:
      - "w9/d3/cardiac/**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore "w9/d3/cardiac/CardiacPatientMonitoring.Tests/CardiacPatientMonitoring.Tests.csproj"

      - name: Build
        run: dotnet build "w9/d3/cardiac/CardiacPatientMonitoring.Tests/CardiacPatientMonitoring.Tests.csproj" --no-restore --configuration Release

      - name: Test
        run: dotnet test "w9/d3/cardiac/CardiacPatientMonitoring.Tests/CardiacPatientMonitoring.Tests.csproj" --no-build --configuration Release --verbosity normal
